### PR TITLE
Just fixed a minor issue

### PR DESCRIPTION
**Pull request by Sapein**
I fixed a minor error by changing #!/bin/sh to #!/bin/bash. So I basically only changed 4 files.

### CODE REVIEW

**Comment by lano1106** [comment]
thank you very much!

**Comment by Sapein** [comment]
No Problem! This should allow compilation on systems that replace sh with a Bash alternative like Dash (Such as Debian and Ubuntu). I might take a look at making them Bourne-Shell Compatible so this way it would be a bit more universal instead of relaying on Bash itself. 

That is if you don't mind.

**Comment by lano1106** [comment]
be my guest! You can be the glcs scripting expert if you want! :-)

**Comment by Sapein** [comment]
Alright, also is the glc-build script used or needed at all?

**Comment by lano1106** [comment]
this is legacy from the original project. I have never personally used it but it did never bother me neither :-)

**Comment by Sapein** [comment]
Okay, I was just wondering because I am having issues making it portable. So I wasn't sure if it's used by this at all or not.

**Comment by Sapein** [comment]
Okay, well I'm mostly done... the reason I asked is because glc-build.sh does a bit of weird things it seems and me making it portable might take a while. However nearly everthing else seems to actually work. It's in my [repo](https://github.com/Sapein/glcs/tree/CompatChanges) if you want to take a look. If you want you can try it out yourself, I haven't completely tested it yet, which is why they are seperate files, and why I haven't suggested to merge it (This way no one is accidentally fucked over by this commit, and I can work on ensuring that everything works.)

**Pull request merged**
